filegroup(
    name = "file",
    srcs = ["Converter.java"],
)

java_binary(
    name = "converter",
    srcs = ["file"],
    main_class = "src.main.java.com.examplebuild.genrule.converter.Converter",
    deps = [],
    visibility = ["//visibility:public"]
)