filegroup(
    name = "csv_expected",
    srcs = ["expected.csv"],
    visibility = ["//src/main/java/com/examplebuild/genrule:__pkg__"]
)

filegroup(
    name = "json_exepected",
    srcs = ["json_expected.json"],
    visibility = ["//src/main/java/com/examplebuild/genrule:__pkg__"]
)